homework_two/lib/book_your_taxi_web/router.ex
defmodule BookYourTaxiWeb.Router do
  use BookYourTaxiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BookYourTaxiWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BookYourTaxi.Authentication, repo: BookYourTaxi.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookYourTaxiWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/taxis", TaxiController, only: [:new, :create, :show]
    resources "/bookings", BookingController, only: [:index, :new, :create, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookYourTaxiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BookYourTaxiWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

homework_two/lib/book_your_taxi_web/views/layout_view.ex
defmodule BookYourTaxiWeb.LayoutView do
  use BookYourTaxiWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

homework_two/lib/book_your_taxi_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

homework_two/lib/book_your_taxi_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

homework_two/lib/book_your_taxi_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "BookYourTaxi", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header class="phx-hero mt-3">
      <h1>Book a Taxi</h1>
      <p>Your destination is just a form away</p>

      <%= if @conn.assigns.current_user do %>
        <%= link "Log out", to: Routes.session_path(@conn, :delete, @conn.assigns.current_user), method: "delete", class: "button" %>
      <% else %>
        <%= link "Log in", to: Routes.session_path(@conn, :new), class: "button" %>
        <%= link "Sign up", to: Routes.user_path(@conn, :new), class: "button" %>
      <% end %>
    </header>

    <%= @inner_content %>
  </body>
</html>