homework_two/lib/book_your_taxi_web/router.ex
defmodule BookYourTaxiWeb.Router do
  use BookYourTaxiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BookYourTaxiWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BookYourTaxi.Authentication, repo: BookYourTaxi.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookYourTaxiWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/taxis", TaxiController, only: [:new, :create, :show]
    resources "/bookings", BookingController, only: [:index, :new, :create, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookYourTaxiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BookYourTaxiWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

homework_two/lib/book_your_taxi/accounts/user.ex
defmodule BookYourTaxi.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :age, :integer
    field :email, :string
    field :full_name, :string
    field :password, :string
    field :role, :string
    has_one :taxi, BookYourTaxi.Sales.Taxi
    has_many :bookings, BookYourTaxi.Sales.Booking

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:full_name, :age, :email, :password, :role])
    |> validate_required([:full_name, :age, :email, :password, :role])
    |> validate_format(:email, ~r/@/)
    |> validate_number(:age, greater_than_or_equal_to: 18)
    |> unique_constraint(:email)
  end
end

homework_two/lib/book_your_taxi_web/controllers/user_controller.ex
defmodule BookYourTaxiWeb.UserController do
  use BookYourTaxiWeb, :controller

  import Ecto.Query

  alias BookYourTaxi.Repo
  alias BookYourTaxi.Sales.Taxi
  alias BookYourTaxi.Accounts.User

  def new(conn, _params) do
    changeset = User.changeset(%User{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    taxi =
      from(t in Taxi, where: t.user_id == ^id)
      |> Repo.one()
      |> Repo.preload(user: :taxi)

    case taxi != nil do
      true  -> render(conn, "show.html", user: user, taxi: taxi, has_taxi: true)
      false -> render(conn, "show.html", user: user, has_taxi: false)
    end
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.session_path(conn, :new))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

homework_two/lib/book_your_taxi_web/views/user_view.ex
defmodule BookYourTaxiWeb.UserView do
  use BookYourTaxiWeb, :view
end

homework_two/lib/book_your_taxi_web/templates/user/customer.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.full_name %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

</ul>

homework_two/lib/book_your_taxi_web/templates/user/driver.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.full_name %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

</ul>

homework_two/lib/book_your_taxi_web/templates/user/new.html.eex
<h2>Sign up</h2>

<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>

<%= form_for @changeset, Routes.user_path(@conn, :create), fn user -> %>
  <div class="form-group">
    <%= label user, :full_name, class: "control-label" %>
    <%= text_input user, :full_name, class: "form-control" %>
    <%= error_tag user, :full_name %>
  </div>
  <div class="form-group">
    <%= label user, :age, class: "control-label" %>
    <%= number_input user, :age, class: "form-control" %>
    <%= error_tag user, :age %>
  </div>
  <div class="form-group">
    <%= label user, :role, class: "control-label" %>
    <%= select user, :role, ["Customer": "customer", "Driver": "driver"], class: "w-100" %>
    <%= error_tag user, :role %>
  </div>
  <div class="form-group">
    <%= label user, :email, class: "control-label" %>
    <%= email_input user, :email, class: "form-control" %>
    <%= error_tag user, :email %>
  </div>
  <div class="form-group">
    <%= label user, :password, class: "control-label" %>
    <%= password_input user, :password, class: "form-control" %>
    <%= error_tag user, :password %>
  </div>
  <div class="form-group">
    <%= submit "Submit", class: "button button-outline" %>
  </div>
<% end %>

homework_two/lib/book_your_taxi_web/templates/user/show.html.eex
<%= if @user.role == "driver" do %>
  <div>
    <h2>My Taxi Information</h2>
    <%= if @has_taxi do %>
      <ul>
        <li><strong>Name:</strong> <%= @user.full_name %></li>
        <li><strong>Email:</strong> <%= @user.email %></li>
        <li><strong>Rate:</strong> <%= @taxi.rate %></li>
        <li><strong>Location:</strong> <%= @taxi.location %></li>
        <li><strong>Status:</strong> <%= @taxi.status %></li>
      </ul>
    <% else %>
      <ul>
        <li><strong>Name:</strong> <%= @user.full_name %></li>
        <li><strong>Email:</strong> <%= @user.email %></li>
      </ul>

      <%= link "Add a taxi", to: Routes.taxi_path(@conn, :new), class: "button" %>
    <% end %>
  </div>

  <div>
    <h2>Active Rides</h2>
    <p>There are no active rides at the moment</p>
  </div>

<% else %>
  <%= link "Book A Taxi", to: Routes.booking_path(@conn, :new), class: "button", id: "book-a-taxi-button" %>
<% end %>